version: "3.9"

services:
  postgres:
    container_name: neuroshima_postgres
    image: postgres:13.3
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    environment:
      - POSTGRES_DB=neuroshima
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

volumes:
  database-data: # named volumes can be managed easier using docker-compose
